import java.util.Random;

public class SortListTest
{
    private List intList;
    private List strList;

    public SortListTest()
    {       
        // Test Int sorting
        intList = new List<Integer>();
        SortedList<Integer> s1 = new SortedList(intList, new IntComp());
        fillInt(20);
        System.out.print("Unsorted: "); intList.Print();
        intList = s1.Sort();
        System.out.print("Sorted:   "); intList.Print(); System.out.println();
        
        // Test string sorting
        strList = new List<String>();
        SortedList<String> s2 = new SortedList(strList, new StrComp());
        fillStr(10);
        System.out.print("Unsorted: "); strList.Print();
        strList = s2.Sort();
        System.out.print("Sorted:   "); strList.Print();
    }

    private void fillInt(int amount) {
        Random rand = new Random();
        for (int i = 0; i <= amount; i++) {
            intList.Push(rand.nextInt(99));    
        }
    }
    
    private void fillStr(int amount) {
        for (int i = 0; i <= amount; i++) {
            strList.Push(getRandomString());    
        }
    }
    
    /**
     * Takes a random ascii character and adds it to a string 
     * @return s  s is a random lowercase string generated by this little script
     */
    private String getRandomString() {
        Random rand = new Random();
        String s = "";
        while(s.length() < 7) {
            int number = rand.nextInt(255);
            if(number > 96 && number < 123) { // small letters ASCII
                s = s  + Character.toString((char)number);
            }
        }
        return s;
    }
    
    /**
     * Callback function to compare our int data.
     * 
     * if (o1 == o2)
     *     return 0;
     * else if (o1 > o2)
     *     return 1;
     * return -1;
     * 
     */
    static class IntComp implements Comperator<Integer> {
        public final int compare(Integer o1, Integer o2) {
            return o1.compareTo(o2);
        }
    }
    
    static class StrComp implements Comperator<String> {
        public final int compare(String o1, String o2) {
            return o1.compareTo(o2);
        }
    }

}